# Generated by Django 5.2.3 on 2025-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='carreras/'),
        ),
    ]
